#rtAudio
list(APPEND OF_LIB_RTAUDIO_INCLUDE "../openFrameworks/libs/rtAudio/include")
list(APPEND OF_LIB_RTAUDIO_LINK "../openFrameworks/libs/rtAudio/lib/osx/rtaudio.a")
add_library(OF_LIB_RTAUDIO INTERFACE ${OF_LIB_RTAUDIO_LINK})

#fmod
list(APPEND OF_LIB_FMOD_INCLUDE "../openFrameworks/libs/fmod/include")
list(APPEND OF_LIB_FMOD_LINK "../openFrameworks/libs/fmod/lib/osx/libfmod.dylib")
add_library(OF_LIB_FMOD INTERFACE ${OF_LIB_FMOD_LINK})

#freetype
list(APPEND OF_LIB_FREETYPE_INCLUDE "../openFrameworks/libs/freetype/include")
list(APPEND OF_LIB_FREETYPE_LINK "../openFrameworks/libs/freetype/lib/osx/freetype.a")
add_library(OF_LIB_FREETYPE INTERFACE ${OF_LIB_FREETYPE_LINK})

#utf8
list(APPEND OF_LIB_UTF8_INCLUDE "../openFrameworks/libs/utf8/include")

#boost
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include")
list(APPEND OF_LIB_BOOST_LINK "../openFrameworks/libs/boost/lib/osx/boost_system.a")
list(APPEND OF_LIB_BOOST_LINK "../openFrameworks/libs/boost/lib/osx/boost_filesystem.a")
add_library(OF_LIB_BOOST INTERFACE ${OF_LIB_BOOST_LINK})

#cairo
list(APPEND OF_LIB_CAIRO_INCLUDE "../openFrameworks/libs/cairo/include")
list(APPEND OF_LIB_CAIRO_LINK "../openFrameworks/libs/cairo/lib/osx/cairo-script-interpreter.a")
list(APPEND OF_LIB_CAIRO_LINK "../openFrameworks/libs/cairo/lib/osx/cairo.a")
list(APPEND OF_LIB_CAIRO_LINK "../openFrameworks/libs/cairo/lib/osx/png.a")
list(APPEND OF_LIB_CAIRO_LINK "../openFrameworks/libs/cairo/lib/osx/pixman-1.a")
add_library(OF_LIB_CAIRO INTERFACE ${OF_LIB_CAIRO_LINK})

#curl
list(APPEND OF_LIB_CURL_INCLUDE "../openFrameworks/libs/curl/include")
list(APPEND OF_LIB_CURL_LINK "../openFrameworks/libs/curl/lib/osx/curl.a")
add_library(OF_LIB_CURL INTERFACE ${OF_LIB_CURL_LINK})

#json
list(APPEND OF_LIB_JSON_INCLUDE "../openFrameworks/libs/json/include")

#openFrameworks
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/libs/openFrameworks")
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/libs/openFrameworks/3d")
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/libs/openFrameworks/video")
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/libs/openFrameworks/types")
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/libs/openFrameworks/app")
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/libs/openFrameworks/utils")
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/libs/openFrameworks/math")
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/libs/openFrameworks/.settings")
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/libs/openFrameworks/gl")
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/libs/openFrameworks/communication")
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/libs/openFrameworks/events")
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/libs/openFrameworks/graphics")
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/libs/openFrameworks/sound")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/3d/ofCamera.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/3d/ofNode.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/3d/of3dPrimitives.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/3d/ofEasyCam.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/3d/of3dUtils.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/video/ofGstVideoPlayer.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/video/ofVideoPlayer.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/video/ofGstUtils.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/video/ofVideoGrabber.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/video/ofGstVideoGrabber.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/types/ofRectangle.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/types/ofBaseTypes.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/types/ofParameterGroup.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/types/ofColor.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/types/ofParameter.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/app/ofBaseApp.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/app/ofAppGlutWindow.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/app/ofAppEGLWindow.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/app/ofMainLoop.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/app/ofAppNoWindow.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/app/ofAppGLFWWindow.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/app/ofAppRunner.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/utils/ofThread.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/utils/ofFpsCounter.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/utils/ofURLFileLoader.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/utils/ofSystemUtils.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/utils/ofLog.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/utils/ofTimer.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/utils/ofFileUtils.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/utils/ofMatrixStack.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/utils/ofUtils.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/utils/ofXml.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/math/ofVec2f.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/math/ofVec4f.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/math/ofMath.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/math/ofMatrix3x3.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/math/ofQuaternion.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/math/ofMatrix4x4.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/gl/ofShadow.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/gl/ofMaterial.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/gl/ofFbo.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/gl/ofShader.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/gl/ofBufferObject.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/gl/ofVboMesh.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/gl/ofGLUtils.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/gl/ofLight.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/gl/ofVbo.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/gl/ofTexture.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/gl/ofGLRenderer.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/communication/ofSerial.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/communication/ofArduino.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/events/ofEvents.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/graphics/ofBitmapFont.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/graphics/ofGraphicsCairo.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/graphics/ofTessellator.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/graphics/ofGraphics.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/graphics/ofGraphicsBaseTypes.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/graphics/ofCairoRenderer.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/graphics/ofRendererCollection.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/graphics/ofPath.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/graphics/ofPixels.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/graphics/of3dGraphics.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/graphics/ofTrueTypeFont.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/graphics/ofImage.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/sound/ofSoundStream.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/sound/ofRtAudioSoundStream.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/sound/ofFmodSoundPlayer.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/sound/ofSoundBaseTypes.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/sound/ofOpenALSoundPlayer.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/sound/ofSoundPlayer.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/sound/ofSoundBuffer.cpp")
add_library(OF_LIB_OPENFRAMEWORKS ${OF_LIB_OPENFRAMEWORKS_LINK})

#tess2
list(APPEND OF_LIB_TESS2_INCLUDE "../openFrameworks/libs/tess2/include")
list(APPEND OF_LIB_TESS2_LINK "../openFrameworks/libs/tess2/lib/osx/tess2.a")
add_library(OF_LIB_TESS2 INTERFACE ${OF_LIB_TESS2_LINK})

#glew
list(APPEND OF_LIB_GLEW_INCLUDE "../openFrameworks/libs/glew/include")
list(APPEND OF_LIB_GLEW_LINK "../openFrameworks/libs/glew/lib/osx/glew.a")
add_library(OF_LIB_GLEW INTERFACE ${OF_LIB_GLEW_LINK})

#pugixml
list(APPEND OF_LIB_PUGIXML_INCLUDE "../openFrameworks/libs/pugixml/include")
list(APPEND OF_LIB_PUGIXML_LINK "../openFrameworks/libs/pugixml/lib/osx/pugixml.a")
add_library(OF_LIB_PUGIXML INTERFACE ${OF_LIB_PUGIXML_LINK})

#glfw
list(APPEND OF_LIB_GLFW_INCLUDE "../openFrameworks/libs/glfw/include")
list(APPEND OF_LIB_GLFW_LINK "../openFrameworks/libs/glfw/lib/osx/glfw3.a")
add_library(OF_LIB_GLFW INTERFACE ${OF_LIB_GLFW_LINK})

#uriparser
list(APPEND OF_LIB_URIPARSER_INCLUDE "../openFrameworks/libs/uriparser/include")
list(APPEND OF_LIB_URIPARSER_LINK "../openFrameworks/libs/uriparser/lib/osx/uriparser.a")
add_library(OF_LIB_URIPARSER INTERFACE ${OF_LIB_URIPARSER_LINK})

#glm
list(APPEND OF_LIB_GLM_INCLUDE "../openFrameworks/libs/glm/include")
list(APPEND OF_LIB_GLM_LINK "../openFrameworks/libs/glm/include/glm/detail/glm.cpp")
add_library(OF_LIB_GLM ${OF_LIB_GLM_LINK})

#FreeImage
list(APPEND OF_LIB_FREEIMAGE_INCLUDE "../openFrameworks/libs/FreeImage/include")
list(APPEND OF_LIB_FREEIMAGE_LINK "../openFrameworks/libs/FreeImage/lib/osx/freeimage.a")
add_library(OF_LIB_FREEIMAGE INTERFACE ${OF_LIB_FREEIMAGE_LINK})

#ofxKinect
list(APPEND OF_ADDON_OFXKINECT_INCLUDE "../openFrameworks/addons/ofxKinect/libs")
list(APPEND OF_ADDON_OFXKINECT_INCLUDE "../openFrameworks/addons/ofxKinect/libs/libusb/include")
list(APPEND OF_ADDON_OFXKINECT_INCLUDE "../openFrameworks/addons/ofxKinect/libs/libfreenect/include")
list(APPEND OF_ADDON_OFXKINECT_INCLUDE "../openFrameworks/addons/ofxKinect/libs/libfreenect/src")
list(APPEND OF_ADDON_OFXKINECT_INCLUDE "../openFrameworks/addons/ofxKinect/src")
list(APPEND OF_ADDON_OFXKINECT_LINK "../openFrameworks/addons/ofxKinect/libs/libusb/lib/osx/usb-1.0.0.a")
list(APPEND OF_ADDON_OFXKINECT_LINK "../openFrameworks/addons/ofxKinect/src/ofxKinect.cpp")
list(APPEND OF_ADDON_OFXKINECT_LINK "../openFrameworks/addons/ofxKinect/src/extra/ofxKinectExtras.cpp")
add_library(OF_ADDON_OFXKINECT ${OF_ADDON_OFXKINECT_LINK})

#ofxGui
list(APPEND OF_ADDON_OFXGUI_INCLUDE "../openFrameworks/addons/ofxGui/src")
list(APPEND OF_ADDON_OFXGUI_LINK "../openFrameworks/addons/ofxGui/src/ofxBaseGui.cpp")
list(APPEND OF_ADDON_OFXGUI_LINK "../openFrameworks/addons/ofxGui/src/ofxColorPicker.cpp")
list(APPEND OF_ADDON_OFXGUI_LINK "../openFrameworks/addons/ofxGui/src/ofxSliderGroup.cpp")
list(APPEND OF_ADDON_OFXGUI_LINK "../openFrameworks/addons/ofxGui/src/ofxToggle.cpp")
list(APPEND OF_ADDON_OFXGUI_LINK "../openFrameworks/addons/ofxGui/src/ofxButton.cpp")
list(APPEND OF_ADDON_OFXGUI_LINK "../openFrameworks/addons/ofxGui/src/ofxGuiGroup.cpp")
list(APPEND OF_ADDON_OFXGUI_LINK "../openFrameworks/addons/ofxGui/src/ofxInputField.cpp")
list(APPEND OF_ADDON_OFXGUI_LINK "../openFrameworks/addons/ofxGui/src/ofxLabel.cpp")
list(APPEND OF_ADDON_OFXGUI_LINK "../openFrameworks/addons/ofxGui/src/ofxPanel.cpp")
list(APPEND OF_ADDON_OFXGUI_LINK "../openFrameworks/addons/ofxGui/src/ofxSlider.cpp")
add_library(OF_ADDON_OFXGUI ${OF_ADDON_OFXGUI_LINK})

#ofxNetwork
list(APPEND OF_ADDON_OFXNETWORK_INCLUDE "../openFrameworks/addons/ofxNetwork/src")
list(APPEND OF_ADDON_OFXNETWORK_LINK "../openFrameworks/addons/ofxNetwork/src/ofxUDPManager.cpp")
list(APPEND OF_ADDON_OFXNETWORK_LINK "../openFrameworks/addons/ofxNetwork/src/ofxTCPServer.cpp")
list(APPEND OF_ADDON_OFXNETWORK_LINK "../openFrameworks/addons/ofxNetwork/src/ofxTCPManager.cpp")
list(APPEND OF_ADDON_OFXNETWORK_LINK "../openFrameworks/addons/ofxNetwork/src/ofxTCPClient.cpp")
list(APPEND OF_ADDON_OFXNETWORK_LINK "../openFrameworks/addons/ofxNetwork/src/ofxNetworkUtils.cpp")
add_library(OF_ADDON_OFXNETWORK ${OF_ADDON_OFXNETWORK_LINK})

#ofxOpenCv
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/src")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libopencv_photo.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libopencv_calib3d.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libquirc.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libopencv_features2d.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libopencv_dnn.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libopencv_core.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/liblibopenjp2.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libopencv_video.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libopencv_ml.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/liblibprotobuf.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libopencv_objdetect.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libzlib.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libopencv_flann.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libittnotify.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libopencv_imgproc.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/src/ofxCvColorImage.cpp")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/src/ofxCvShortImage.cpp")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/src/ofxCvContourFinder.cpp")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/src/ofxCvHaarFinder.cpp")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/src/ofxCvImage.cpp")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/src/ofxCvFloatImage.cpp")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/src/ofxCvGrayscaleImage.cpp")
add_library(OF_ADDON_OFXOPENCV ${OF_ADDON_OFXOPENCV_LINK})

#ofxPoco
list(APPEND OF_ADDON_OFXPOCO_INCLUDE "../openFrameworks/addons/ofxPoco/libs")
list(APPEND OF_ADDON_OFXPOCO_INCLUDE "../openFrameworks/addons/ofxPoco/libs/openssl/include")
list(APPEND OF_ADDON_OFXPOCO_INCLUDE "../openFrameworks/addons/ofxPoco/libs/poco/include")
list(APPEND OF_ADDON_OFXPOCO_LINK "../openFrameworks/addons/ofxPoco/libs/openssl/lib/osx/crypto.a")
list(APPEND OF_ADDON_OFXPOCO_LINK "../openFrameworks/addons/ofxPoco/libs/openssl/lib/osx/ssl.a")
list(APPEND OF_ADDON_OFXPOCO_LINK "../openFrameworks/addons/ofxPoco/libs/poco/lib/osx/PocoFoundation.a")
list(APPEND OF_ADDON_OFXPOCO_LINK "../openFrameworks/addons/ofxPoco/libs/poco/lib/osx/PocoUtil.a")
list(APPEND OF_ADDON_OFXPOCO_LINK "../openFrameworks/addons/ofxPoco/libs/poco/lib/osx/PocoJWT.a")
list(APPEND OF_ADDON_OFXPOCO_LINK "../openFrameworks/addons/ofxPoco/libs/poco/lib/osx/PocoJSON.a")
list(APPEND OF_ADDON_OFXPOCO_LINK "../openFrameworks/addons/ofxPoco/libs/poco/lib/osx/PocoCrypto.a")
list(APPEND OF_ADDON_OFXPOCO_LINK "../openFrameworks/addons/ofxPoco/libs/poco/lib/osx/PocoEncodings.a")
list(APPEND OF_ADDON_OFXPOCO_LINK "../openFrameworks/addons/ofxPoco/libs/poco/lib/osx/PocoRedis.a")
list(APPEND OF_ADDON_OFXPOCO_LINK "../openFrameworks/addons/ofxPoco/libs/poco/lib/osx/PocoNet.a")
list(APPEND OF_ADDON_OFXPOCO_LINK "../openFrameworks/addons/ofxPoco/libs/poco/lib/osx/PocoXML.a")
list(APPEND OF_ADDON_OFXPOCO_LINK "../openFrameworks/addons/ofxPoco/libs/poco/lib/osx/PocoNetSSL.a")
list(APPEND OF_ADDON_OFXPOCO_LINK "../openFrameworks/addons/ofxPoco/libs/poco/lib/osx/PocoZip.a")
add_library(OF_ADDON_OFXPOCO INTERFACE ${OF_ADDON_OFXPOCO_LINK})

#ofxVectorGraphics
list(APPEND OF_ADDON_OFXVECTORGRAPHICS_INCLUDE "../openFrameworks/addons/ofxVectorGraphics/libs")
list(APPEND OF_ADDON_OFXVECTORGRAPHICS_INCLUDE "../openFrameworks/addons/ofxVectorGraphics/src")
list(APPEND OF_ADDON_OFXVECTORGRAPHICS_LINK "../openFrameworks/addons/ofxVectorGraphics/libs/CreEPS.cpp")
list(APPEND OF_ADDON_OFXVECTORGRAPHICS_LINK "../openFrameworks/addons/ofxVectorGraphics/src/ofxVectorGraphics.cpp")
add_library(OF_ADDON_OFXVECTORGRAPHICS ${OF_ADDON_OFXVECTORGRAPHICS_LINK})

#ofxXmlSettings
list(APPEND OF_ADDON_OFXXMLSETTINGS_INCLUDE "../openFrameworks/addons/ofxXmlSettings/libs")
list(APPEND OF_ADDON_OFXXMLSETTINGS_INCLUDE "../openFrameworks/addons/ofxXmlSettings/src")
list(APPEND OF_ADDON_OFXXMLSETTINGS_LINK "../openFrameworks/addons/ofxXmlSettings/libs/tinyxmlparser.cpp")
list(APPEND OF_ADDON_OFXXMLSETTINGS_LINK "../openFrameworks/addons/ofxXmlSettings/libs/tinyxmlerror.cpp")
list(APPEND OF_ADDON_OFXXMLSETTINGS_LINK "../openFrameworks/addons/ofxXmlSettings/libs/tinyxml.cpp")
list(APPEND OF_ADDON_OFXXMLSETTINGS_LINK "../openFrameworks/addons/ofxXmlSettings/src/ofxXmlSettings.cpp")
add_library(OF_ADDON_OFXXMLSETTINGS ${OF_ADDON_OFXXMLSETTINGS_LINK})

#ofxEmscripten
list(APPEND OF_ADDON_OFXEMSCRIPTEN_INCLUDE "../openFrameworks/addons/ofxEmscripten/libs")
list(APPEND OF_ADDON_OFXEMSCRIPTEN_INCLUDE "../openFrameworks/addons/ofxEmscripten/libs/html5video/include")
list(APPEND OF_ADDON_OFXEMSCRIPTEN_INCLUDE "../openFrameworks/addons/ofxEmscripten/libs/html5audio/include")
list(APPEND OF_ADDON_OFXEMSCRIPTEN_INCLUDE "../openFrameworks/addons/ofxEmscripten/src")
list(APPEND OF_ADDON_OFXEMSCRIPTEN_LINK "../openFrameworks/addons/ofxEmscripten/src/ofxEmscriptenSoundStream.cpp")
list(APPEND OF_ADDON_OFXEMSCRIPTEN_LINK "../openFrameworks/addons/ofxEmscripten/src/ofxEmscriptenVideoPlayer.cpp")
list(APPEND OF_ADDON_OFXEMSCRIPTEN_LINK "../openFrameworks/addons/ofxEmscripten/src/ofxEmscriptenSoundPlayer.cpp")
list(APPEND OF_ADDON_OFXEMSCRIPTEN_LINK "../openFrameworks/addons/ofxEmscripten/src/ofxEmscriptenVideoGrabber.cpp")
list(APPEND OF_ADDON_OFXEMSCRIPTEN_LINK "../openFrameworks/addons/ofxEmscripten/src/ofxEmscriptenURLFileLoader.cpp")
list(APPEND OF_ADDON_OFXEMSCRIPTEN_LINK "../openFrameworks/addons/ofxEmscripten/src/ofxAppEmscriptenWindow.cpp")
add_library(OF_ADDON_OFXEMSCRIPTEN ${OF_ADDON_OFXEMSCRIPTEN_LINK})

#ofxAccelerometer
list(APPEND OF_ADDON_OFXACCELEROMETER_INCLUDE "../openFrameworks/addons/ofxAccelerometer/src")
list(APPEND OF_ADDON_OFXACCELEROMETER_LINK "../openFrameworks/addons/ofxAccelerometer/src/ofxAccelerometer.cpp")
add_library(OF_ADDON_OFXACCELEROMETER ${OF_ADDON_OFXACCELEROMETER_LINK})

#ofxSvg
list(APPEND OF_ADDON_OFXSVG_INCLUDE "../openFrameworks/addons/ofxSvg/libs")
list(APPEND OF_ADDON_OFXSVG_INCLUDE "../openFrameworks/addons/ofxSvg/libs/libxml2/include")
list(APPEND OF_ADDON_OFXSVG_INCLUDE "../openFrameworks/addons/ofxSvg/libs/svgtiny/include")
list(APPEND OF_ADDON_OFXSVG_INCLUDE "../openFrameworks/addons/ofxSvg/src")
list(APPEND OF_ADDON_OFXSVG_LINK "../openFrameworks/addons/ofxSvg/libs/libxml2/lib/osx/xml2.a")
list(APPEND OF_ADDON_OFXSVG_LINK "../openFrameworks/addons/ofxSvg/libs/svgtiny/lib/osx/svgtiny.a")
list(APPEND OF_ADDON_OFXSVG_LINK "../openFrameworks/addons/ofxSvg/src/ofxSvg.cpp")
add_library(OF_ADDON_OFXSVG ${OF_ADDON_OFXSVG_LINK})

#ofxOsc
list(APPEND OF_ADDON_OFXOSC_INCLUDE "../openFrameworks/addons/ofxOsc/libs")
list(APPEND OF_ADDON_OFXOSC_INCLUDE "../openFrameworks/addons/ofxOsc/libs/oscpack/src")
list(APPEND OF_ADDON_OFXOSC_INCLUDE "../openFrameworks/addons/ofxOsc/src")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/libs/oscpack/src/osc/OscOutboundPacketStream.cpp")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/libs/oscpack/src/osc/OscTypes.cpp")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/libs/oscpack/src/osc/OscReceivedElements.cpp")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/libs/oscpack/src/osc/OscPrintReceivedElements.cpp")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/libs/oscpack/src/ip/IpEndpointName.cpp")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/libs/oscpack/src/ip/posix/NetworkingUtils.cpp")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/libs/oscpack/src/ip/posix/UdpSocket.cpp")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/src/ofxOscParameterSync.cpp")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/src/ofxOscMessage.cpp")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/src/ofxOscBundle.cpp")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/src/ofxOscReceiver.cpp")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/src/ofxOscSender.cpp")
add_library(OF_ADDON_OFXOSC ${OF_ADDON_OFXOSC_LINK})

#ofxGPS
list(APPEND OF_ADDON_OFXGPS_INCLUDE "../openFrameworks/addons/ofxGPS/src")
list(APPEND OF_ADDON_OFXGPS_LINK "../openFrameworks/addons/ofxGPS/src/Android/ofxGPSImplAndroid.cpp")
add_library(OF_ADDON_OFXGPS ${OF_ADDON_OFXGPS_LINK})

#ofxUnitTests
list(APPEND OF_ADDON_OFXUNITTESTS_INCLUDE "../openFrameworks/addons/ofxUnitTests/src")

#ofxThreadedImageLoader
list(APPEND OF_ADDON_OFXTHREADEDIMAGELOADER_INCLUDE "../openFrameworks/addons/ofxThreadedImageLoader/src")
list(APPEND OF_ADDON_OFXTHREADEDIMAGELOADER_LINK "../openFrameworks/addons/ofxThreadedImageLoader/src/ofxThreadedImageLoader.cpp")
add_library(OF_ADDON_OFXTHREADEDIMAGELOADER ${OF_ADDON_OFXTHREADEDIMAGELOADER_LINK})

#ofxAndroid
list(APPEND OF_ADDON_OFXANDROID_INCLUDE "../openFrameworks/addons/ofxAndroid/ofAndroidLib/src")
list(APPEND OF_ADDON_OFXANDROID_INCLUDE "../openFrameworks/addons/ofxAndroid/src")
list(APPEND OF_ADDON_OFXANDROID_LINK "../openFrameworks/addons/ofxAndroid/src/ofxAndroidSoundPlayer.cpp")
list(APPEND OF_ADDON_OFXANDROID_LINK "../openFrameworks/addons/ofxAndroid/src/ofxAndroidVideoGrabber.cpp")
list(APPEND OF_ADDON_OFXANDROID_LINK "../openFrameworks/addons/ofxAndroid/src/ofxAndroidUtils.cpp")
list(APPEND OF_ADDON_OFXANDROID_LINK "../openFrameworks/addons/ofxAndroid/src/ofAppAndroidWindow.cpp")
list(APPEND OF_ADDON_OFXANDROID_LINK "../openFrameworks/addons/ofxAndroid/src/ofxAndroidSoundStream.cpp")
list(APPEND OF_ADDON_OFXANDROID_LINK "../openFrameworks/addons/ofxAndroid/src/ofxAndroidAccelerometer.cpp")
list(APPEND OF_ADDON_OFXANDROID_LINK "../openFrameworks/addons/ofxAndroid/src/ofxAndroidVibrator.cpp")
list(APPEND OF_ADDON_OFXANDROID_LINK "../openFrameworks/addons/ofxAndroid/src/ofxAndroidLogChannel.cpp")
list(APPEND OF_ADDON_OFXANDROID_LINK "../openFrameworks/addons/ofxAndroid/src/ofxAndroidVideoPlayer.cpp")
add_library(OF_ADDON_OFXANDROID ${OF_ADDON_OFXANDROID_LINK})

#ofxAssimpModelLoader
list(APPEND OF_ADDON_OFXASSIMPMODELLOADER_INCLUDE "../openFrameworks/addons/ofxAssimpModelLoader/libs")
list(APPEND OF_ADDON_OFXASSIMPMODELLOADER_INCLUDE "../openFrameworks/addons/ofxAssimpModelLoader/libs/assimp/include")
list(APPEND OF_ADDON_OFXASSIMPMODELLOADER_INCLUDE "../openFrameworks/addons/ofxAssimpModelLoader/src")
list(APPEND OF_ADDON_OFXASSIMPMODELLOADER_LINK "../openFrameworks/addons/ofxAssimpModelLoader/libs/assimp/lib/osx/assimp.a")
list(APPEND OF_ADDON_OFXASSIMPMODELLOADER_LINK "../openFrameworks/addons/ofxAssimpModelLoader/src/ofxAssimpMeshHelper.cpp")
list(APPEND OF_ADDON_OFXASSIMPMODELLOADER_LINK "../openFrameworks/addons/ofxAssimpModelLoader/src/ofxAssimpAnimation.cpp")
list(APPEND OF_ADDON_OFXASSIMPMODELLOADER_LINK "../openFrameworks/addons/ofxAssimpModelLoader/src/ofxAssimpTexture.cpp")
list(APPEND OF_ADDON_OFXASSIMPMODELLOADER_LINK "../openFrameworks/addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.cpp")
add_library(OF_ADDON_OFXASSIMPMODELLOADER ${OF_ADDON_OFXASSIMPMODELLOADER_LINK})

#ofxiOS
list(APPEND OF_ADDON_OFXIOS_INCLUDE "../openFrameworks/addons/ofxiOS/src")
list(APPEND OF_ADDON_OFXIOS_LINK "../openFrameworks/addons/ofxiOS/src/sound/ofxOpenALSoundPlayer.cpp")
list(APPEND OF_ADDON_OFXIOS_LINK "../openFrameworks/addons/ofxiOS/src/sound/SoundEngine.cpp")
add_library(OF_ADDON_OFXIOS ${OF_ADDON_OFXIOS_LINK})
