#rtAudio
list(APPEND OF_LIB_RTAUDIO_INCLUDE "../openFrameworks/rtAudio")
list(APPEND OF_LIB_RTAUDIO_INCLUDE "../openFrameworks/libs/rtAudio/include")
list(APPEND OF_LIB_RTAUDIO_INCLUDE "../openFrameworks/libs/rtAudio")
list(APPEND OF_LIB_RTAUDIO_LINK "../openFrameworks/libs/rtAudio/lib/osx/rtaudio.a")
add_library(OF_LIB_RTAUDIO INTERFACE ${OF_LIB_RTAUDIO_LINK})

#fmod
list(APPEND OF_LIB_FMOD_INCLUDE "../openFrameworks/fmod")
list(APPEND OF_LIB_FMOD_INCLUDE "../openFrameworks/libs/fmod/include")
list(APPEND OF_LIB_FMOD_INCLUDE "../openFrameworks/libs/fmod")
list(APPEND OF_LIB_FMOD_LINK "../openFrameworks/libs/fmod/lib/osx/libfmod.dylib")
add_library(OF_LIB_FMOD INTERFACE ${OF_LIB_FMOD_LINK})

#freetype
list(APPEND OF_LIB_FREETYPE_INCLUDE "../openFrameworks/freetype")
list(APPEND OF_LIB_FREETYPE_INCLUDE "../openFrameworks/libs/freetype/include/freetype2")
list(APPEND OF_LIB_FREETYPE_INCLUDE "../openFrameworks/libs/freetype/include")
list(APPEND OF_LIB_FREETYPE_INCLUDE "../openFrameworks/libs/freetype")
list(APPEND OF_LIB_FREETYPE_INCLUDE "../openFrameworks/libs/freetype/include/freetype2/freetype")
list(APPEND OF_LIB_FREETYPE_INCLUDE "../openFrameworks/libs/freetype/include/freetype2/freetype/config")
list(APPEND OF_LIB_FREETYPE_INCLUDE "../openFrameworks/libs/freetype/include/freetype2/freetype/internal")
list(APPEND OF_LIB_FREETYPE_INCLUDE "../openFrameworks/libs/freetype/include/freetype2/freetype/internal/services")
list(APPEND OF_LIB_FREETYPE_LINK "../openFrameworks/libs/freetype/lib/osx/freetype.a")
add_library(OF_LIB_FREETYPE INTERFACE ${OF_LIB_FREETYPE_LINK})

#utf8
list(APPEND OF_LIB_UTF8_INCLUDE "../openFrameworks/utf8")
list(APPEND OF_LIB_UTF8_INCLUDE "../openFrameworks/libs/utf8/include")
list(APPEND OF_LIB_UTF8_INCLUDE "../openFrameworks/libs/utf8")
list(APPEND OF_LIB_UTF8_INCLUDE "../openFrameworks/libs/utf8/include/utf8")

#boost
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/boost")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/move")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/move/algo")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/move/algo/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/move/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/core")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/test")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/test/tree")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/test/tools")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/test/tools/old")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/test/tools/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/test/output")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/test/utils")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/test/utils/runtime")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/test/utils/runtime/cla")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/test/utils/runtime/env")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/test/utils/iterator")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/test/utils/basic_cstring")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/test/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/test/included")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/chrono")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/chrono/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/chrono/detail/inlined")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/chrono/detail/inlined/posix")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/chrono/detail/inlined/win")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/chrono/detail/inlined/mac")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/tuple")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/tuple/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/config")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/config/platform")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/config/abi")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/config/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/config/no_tr1")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/config/stdlib")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/config/compiler")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/smart_ptr")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/smart_ptr/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/timer")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/type_traits")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/type_traits/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/io")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/io/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/filesystem")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/filesystem/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/function")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/function/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/algorithm/cxx11")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/algorithm")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/algorithm/string")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/algorithm/string/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/regex")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/regex/config")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/regex/v4")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/regex/pending")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/date_time")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/date_time/gregorian")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/date_time/posix_time")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/atomic")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/atomic/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/atomic/detail/type_traits")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/math/tools")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/math")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/math/policies")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/math/special_functions")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/math/special_functions/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/ratio")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/ratio/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/ratio/detail/mpl")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/ratio/mpl")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/optional")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/optional/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/container")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/container/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/system")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/system/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/iterator")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/iterator/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/numeric/conversion")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/numeric")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/numeric/conversion/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/numeric/conversion/detail/preprocessed")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/detail/winapi")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/detail/winapi/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/intrusive")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/intrusive/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/concept")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/concept/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/limits")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/list")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/list/aux_")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/list/aux_/preprocessed/plain")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/list/aux_/preprocessed")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/aux_")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/aux_/config")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/aux_/preprocessed/no_ctps")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/aux_/preprocessed")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/aux_/preprocessed/msvc70")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/aux_/preprocessed/plain")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/aux_/preprocessed/dmc")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/aux_/preprocessed/bcc551")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/aux_/preprocessed/gcc")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/aux_/preprocessed/mwcw")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/aux_/preprocessed/no_ttp")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/aux_/preprocessed/msvc60")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/aux_/preprocessed/bcc")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/aux_/preprocessed/bcc_pre590")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/aux_/preprocessor")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/vector")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/vector/aux_")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/vector/aux_/preprocessed/no_ctps")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/vector/aux_/preprocessed")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/vector/aux_/preprocessed/plain")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/mpl/vector/aux_/preprocessed/typeof_based")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/winapi")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/integer")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/predef")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/predef/hardware")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/predef/hardware/simd")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/predef/hardware/simd/x86_amd")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/predef/hardware/simd/ppc")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/predef/hardware/simd/x86")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/predef/hardware/simd/arm")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/predef/platform")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/predef/other")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/predef/library")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/predef/library/std")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/predef/library/c")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/predef/language")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/predef/architecture")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/predef/architecture/x86")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/predef/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/predef/os")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/predef/os/bsd")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/predef/compiler")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/range")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/range/algorithm")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/range/adaptor")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/range/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/bind")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/thread")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/thread/futures")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/thread/pthread")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/thread/v2")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/thread/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/thread/executors")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/thread/csbl")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/thread/csbl/memory")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/thread/win32")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/exception")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/exception/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/repetition")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/repetition/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/repetition/detail/edg")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/repetition/detail/msvc")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/repetition/detail/dmc")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/variadic")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/tuple")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/tuple/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/config")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/array")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/seq")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/seq/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/detail/dmc")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/list")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/list/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/list/detail/edg")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/list/detail/dmc")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/logical")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/punctuation")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/punctuation/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/arithmetic")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/arithmetic/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/comparison")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/iteration")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/iteration/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/iteration/detail/bounds")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/iteration/detail/iter")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/slot")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/slot/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/control")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/control/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/control/detail/edg")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/control/detail/msvc")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/control/detail/dmc")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/facilities")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/facilities/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/preprocessor/debug")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/functional")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/functional/hash")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/functional/hash/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/type_index")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/type_index/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/lexical_cast")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/lexical_cast/detail")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/utility")
list(APPEND OF_LIB_BOOST_INCLUDE "../openFrameworks/libs/boost/include/boost/utility/detail")
list(APPEND OF_LIB_BOOST_LINK "../openFrameworks/libs/boost/lib/osx/boost_system.a")
list(APPEND OF_LIB_BOOST_LINK "../openFrameworks/libs/boost/lib/osx/boost_filesystem.a")
add_library(OF_LIB_BOOST INTERFACE ${OF_LIB_BOOST_LINK})

#cairo
list(APPEND OF_LIB_CAIRO_INCLUDE "../openFrameworks/cairo")
list(APPEND OF_LIB_CAIRO_INCLUDE "../openFrameworks/libs/cairo/include/cairo")
list(APPEND OF_LIB_CAIRO_INCLUDE "../openFrameworks/libs/cairo/include")
list(APPEND OF_LIB_CAIRO_INCLUDE "../openFrameworks/libs/cairo")
list(APPEND OF_LIB_CAIRO_LINK "../openFrameworks/libs/cairo/lib/osx/cairo-script-interpreter.a")
list(APPEND OF_LIB_CAIRO_LINK "../openFrameworks/libs/cairo/lib/osx/cairo.a")
list(APPEND OF_LIB_CAIRO_LINK "../openFrameworks/libs/cairo/lib/osx/png.a")
list(APPEND OF_LIB_CAIRO_LINK "../openFrameworks/libs/cairo/lib/osx/pixman-1.a")
add_library(OF_LIB_CAIRO INTERFACE ${OF_LIB_CAIRO_LINK})

#curl
list(APPEND OF_LIB_CURL_INCLUDE "../openFrameworks/curl")
list(APPEND OF_LIB_CURL_INCLUDE "../openFrameworks/libs/curl/include/curl")
list(APPEND OF_LIB_CURL_INCLUDE "../openFrameworks/libs/curl/include")
list(APPEND OF_LIB_CURL_INCLUDE "../openFrameworks/libs/curl")
list(APPEND OF_LIB_CURL_LINK "../openFrameworks/libs/curl/lib/osx/curl.a")
add_library(OF_LIB_CURL INTERFACE ${OF_LIB_CURL_LINK})

#json
list(APPEND OF_LIB_JSON_INCLUDE "../openFrameworks/json")
list(APPEND OF_LIB_JSON_INCLUDE "../openFrameworks/libs/json/include")
list(APPEND OF_LIB_JSON_INCLUDE "../openFrameworks/libs/json")

#openFrameworks
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/openFrameworks")
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/libs/openFrameworks")
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/libs/openFrameworks/3d")
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/libs/openFrameworks/video")
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/libs/openFrameworks/types")
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/libs/openFrameworks/app")
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/libs/openFrameworks/utils")
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/libs/openFrameworks/math")
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/libs/openFrameworks/gl")
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/libs/openFrameworks/communication")
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/libs/openFrameworks/events")
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/libs/openFrameworks/graphics")
list(APPEND OF_LIB_OPENFRAMEWORKS_INCLUDE "../openFrameworks/libs/openFrameworks/sound")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/3d/ofCamera.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/3d/ofNode.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/3d/of3dPrimitives.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/3d/ofEasyCam.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/3d/of3dUtils.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/video/ofGstVideoPlayer.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/video/ofVideoPlayer.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/video/ofDirectShowPlayer.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/video/ofGstUtils.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/video/ofVideoGrabber.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/video/ofGstVideoGrabber.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/video/ofDirectShowGrabber.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/types/ofRectangle.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/types/ofBaseTypes.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/types/ofParameterGroup.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/types/ofColor.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/types/ofParameter.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/app/ofBaseApp.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/app/ofAppGlutWindow.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/app/ofAppEGLWindow.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/app/ofMainLoop.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/app/ofAppNoWindow.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/app/ofAppGLFWWindow.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/app/ofAppRunner.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/utils/ofThread.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/utils/ofFpsCounter.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/utils/ofURLFileLoader.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/utils/ofSystemUtils.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/utils/ofLog.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/utils/ofTimer.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/utils/ofFileUtils.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/utils/ofMatrixStack.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/utils/ofUtils.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/utils/ofXml.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/math/ofVec2f.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/math/ofVec4f.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/math/ofMath.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/math/ofMatrix3x3.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/math/ofQuaternion.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/math/ofMatrix4x4.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/gl/ofShadow.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/gl/ofMaterial.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/gl/ofFbo.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/gl/ofShader.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/gl/ofBufferObject.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/gl/ofVboMesh.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/gl/ofGLUtils.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/gl/ofLight.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/gl/ofVbo.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/gl/ofTexture.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/gl/ofGLRenderer.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/communication/ofSerial.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/communication/ofArduino.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/events/ofEvents.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/graphics/ofBitmapFont.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/graphics/ofGraphicsCairo.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/graphics/ofTessellator.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/graphics/ofGraphics.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/graphics/ofGraphicsBaseTypes.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/graphics/ofCairoRenderer.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/graphics/ofRendererCollection.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/graphics/ofPath.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/graphics/ofPixels.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/graphics/of3dGraphics.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/graphics/ofTrueTypeFont.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/graphics/ofImage.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/sound/ofSoundStream.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/sound/ofRtAudioSoundStream.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/sound/ofFmodSoundPlayer.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/sound/ofSoundBaseTypes.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/sound/ofOpenALSoundPlayer.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/sound/ofSoundPlayer.cpp")
list(APPEND OF_LIB_OPENFRAMEWORKS_LINK "../openFrameworks/libs/openFrameworks/sound/ofSoundBuffer.cpp")
add_library(OF_LIB_OPENFRAMEWORKS ${OF_LIB_OPENFRAMEWORKS_LINK})

#tess2
list(APPEND OF_LIB_TESS2_INCLUDE "../openFrameworks/tess2")
list(APPEND OF_LIB_TESS2_INCLUDE "../openFrameworks/libs/tess2/include")
list(APPEND OF_LIB_TESS2_INCLUDE "../openFrameworks/libs/tess2")
list(APPEND OF_LIB_TESS2_LINK "../openFrameworks/libs/tess2/lib/osx/tess2.a")
add_library(OF_LIB_TESS2 INTERFACE ${OF_LIB_TESS2_LINK})

#glew
list(APPEND OF_LIB_GLEW_INCLUDE "../openFrameworks/glew")
list(APPEND OF_LIB_GLEW_INCLUDE "../openFrameworks/libs/glew/include/GL")
list(APPEND OF_LIB_GLEW_INCLUDE "../openFrameworks/libs/glew/include")
list(APPEND OF_LIB_GLEW_INCLUDE "../openFrameworks/libs/glew")
list(APPEND OF_LIB_GLEW_LINK "../openFrameworks/libs/glew/lib/osx/glew.a")
add_library(OF_LIB_GLEW INTERFACE ${OF_LIB_GLEW_LINK})

#pugixml
list(APPEND OF_LIB_PUGIXML_INCLUDE "../openFrameworks/pugixml")
list(APPEND OF_LIB_PUGIXML_INCLUDE "../openFrameworks/libs/pugixml/include")
list(APPEND OF_LIB_PUGIXML_INCLUDE "../openFrameworks/libs/pugixml")
list(APPEND OF_LIB_PUGIXML_LINK "../openFrameworks/libs/pugixml/lib/osx/pugixml.a")
add_library(OF_LIB_PUGIXML INTERFACE ${OF_LIB_PUGIXML_LINK})

#glfw
list(APPEND OF_LIB_GLFW_INCLUDE "../openFrameworks/glfw")
list(APPEND OF_LIB_GLFW_INCLUDE "../openFrameworks/libs/glfw/include/GLFW")
list(APPEND OF_LIB_GLFW_INCLUDE "../openFrameworks/libs/glfw/include")
list(APPEND OF_LIB_GLFW_INCLUDE "../openFrameworks/libs/glfw")
list(APPEND OF_LIB_GLFW_LINK "../openFrameworks/libs/glfw/lib/osx/glfw3.a")
add_library(OF_LIB_GLFW INTERFACE ${OF_LIB_GLFW_LINK})

#uriparser
list(APPEND OF_LIB_URIPARSER_INCLUDE "../openFrameworks/uriparser")
list(APPEND OF_LIB_URIPARSER_INCLUDE "../openFrameworks/libs/uriparser/include/uriparser")
list(APPEND OF_LIB_URIPARSER_INCLUDE "../openFrameworks/libs/uriparser/include")
list(APPEND OF_LIB_URIPARSER_INCLUDE "../openFrameworks/libs/uriparser")
list(APPEND OF_LIB_URIPARSER_LINK "../openFrameworks/libs/uriparser/lib/osx/uriparser.a")
add_library(OF_LIB_URIPARSER INTERFACE ${OF_LIB_URIPARSER_LINK})

#glm
list(APPEND OF_LIB_GLM_INCLUDE "../openFrameworks/glm")
list(APPEND OF_LIB_GLM_INCLUDE "../openFrameworks/libs/glm/include/glm")
list(APPEND OF_LIB_GLM_INCLUDE "../openFrameworks/libs/glm/include")
list(APPEND OF_LIB_GLM_INCLUDE "../openFrameworks/libs/glm")
list(APPEND OF_LIB_GLM_INCLUDE "../openFrameworks/libs/glm/include/glm/ext")
list(APPEND OF_LIB_GLM_INCLUDE "../openFrameworks/libs/glm/include/glm/simd")
list(APPEND OF_LIB_GLM_INCLUDE "../openFrameworks/libs/glm/include/glm/detail")
list(APPEND OF_LIB_GLM_INCLUDE "../openFrameworks/libs/glm/include/glm/gtc")
list(APPEND OF_LIB_GLM_INCLUDE "../openFrameworks/libs/glm/include/glm/gtx")
list(APPEND OF_LIB_GLM_LINK "../openFrameworks/libs/glm/include/glm/detail/glm.cpp")
add_library(OF_LIB_GLM ${OF_LIB_GLM_LINK})

#FreeImage
list(APPEND OF_LIB_FREEIMAGE_INCLUDE "../openFrameworks/FreeImage")
list(APPEND OF_LIB_FREEIMAGE_INCLUDE "../openFrameworks/libs/FreeImage/include")
list(APPEND OF_LIB_FREEIMAGE_INCLUDE "../openFrameworks/libs/FreeImage")
list(APPEND OF_LIB_FREEIMAGE_LINK "../openFrameworks/libs/FreeImage/lib/osx/freeimage.a")
add_library(OF_LIB_FREEIMAGE INTERFACE ${OF_LIB_FREEIMAGE_LINK})

#ofxKinect
list(APPEND OF_ADDON_OFXKINECT_INCLUDE "../openFrameworks/addons/ofxKinect/libs/libusb/include")
list(APPEND OF_ADDON_OFXKINECT_INCLUDE "../openFrameworks/addons/ofxKinect/libs/libusb")
list(APPEND OF_ADDON_OFXKINECT_INCLUDE "../openFrameworks/addons/ofxKinect/libs")
list(APPEND OF_ADDON_OFXKINECT_INCLUDE "../openFrameworks/addons/ofxKinect/libs/libfreenect/include")
list(APPEND OF_ADDON_OFXKINECT_INCLUDE "../openFrameworks/addons/ofxKinect/libs/libfreenect")
list(APPEND OF_ADDON_OFXKINECT_INCLUDE "../openFrameworks/addons/ofxKinect/libs/libfreenect/platform")
list(APPEND OF_ADDON_OFXKINECT_INCLUDE "../openFrameworks/addons/ofxKinect/libs/libfreenect/src")
list(APPEND OF_ADDON_OFXKINECT_INCLUDE "../openFrameworks/addons/ofxKinect/src")
list(APPEND OF_ADDON_OFXKINECT_INCLUDE "../openFrameworks/addons/ofxKinect")
list(APPEND OF_ADDON_OFXKINECT_INCLUDE "../openFrameworks/addons/ofxKinect/src/extra")
list(APPEND OF_ADDON_OFXKINECT_LINK "../openFrameworks/addons/ofxKinect/libs/libusb/lib/osx/usb-1.0.0.a")
list(APPEND OF_ADDON_OFXKINECT_LINK "../openFrameworks/addons/ofxKinect/src/ofxKinect.cpp")
list(APPEND OF_ADDON_OFXKINECT_LINK "../openFrameworks/addons/ofxKinect/src/extra/ofxKinectExtras.cpp")
add_library(OF_ADDON_OFXKINECT ${OF_ADDON_OFXKINECT_LINK})

#ofxGui
list(APPEND OF_ADDON_OFXGUI_INCLUDE "../openFrameworks/addons/ofxGui/src")
list(APPEND OF_ADDON_OFXGUI_INCLUDE "../openFrameworks/addons/ofxGui")
list(APPEND OF_ADDON_OFXGUI_LINK "../openFrameworks/addons/ofxGui/src/ofxBaseGui.cpp")
list(APPEND OF_ADDON_OFXGUI_LINK "../openFrameworks/addons/ofxGui/src/ofxColorPicker.cpp")
list(APPEND OF_ADDON_OFXGUI_LINK "../openFrameworks/addons/ofxGui/src/ofxSliderGroup.cpp")
list(APPEND OF_ADDON_OFXGUI_LINK "../openFrameworks/addons/ofxGui/src/ofxToggle.cpp")
list(APPEND OF_ADDON_OFXGUI_LINK "../openFrameworks/addons/ofxGui/src/ofxButton.cpp")
list(APPEND OF_ADDON_OFXGUI_LINK "../openFrameworks/addons/ofxGui/src/ofxGuiGroup.cpp")
list(APPEND OF_ADDON_OFXGUI_LINK "../openFrameworks/addons/ofxGui/src/ofxInputField.cpp")
list(APPEND OF_ADDON_OFXGUI_LINK "../openFrameworks/addons/ofxGui/src/ofxLabel.cpp")
list(APPEND OF_ADDON_OFXGUI_LINK "../openFrameworks/addons/ofxGui/src/ofxPanel.cpp")
list(APPEND OF_ADDON_OFXGUI_LINK "../openFrameworks/addons/ofxGui/src/ofxSlider.cpp")
add_library(OF_ADDON_OFXGUI ${OF_ADDON_OFXGUI_LINK})

#ofxNetwork
list(APPEND OF_ADDON_OFXNETWORK_INCLUDE "../openFrameworks/addons/ofxNetwork/src")
list(APPEND OF_ADDON_OFXNETWORK_INCLUDE "../openFrameworks/addons/ofxNetwork")
list(APPEND OF_ADDON_OFXNETWORK_LINK "../openFrameworks/addons/ofxNetwork/src/ofxUDPManager.cpp")
list(APPEND OF_ADDON_OFXNETWORK_LINK "../openFrameworks/addons/ofxNetwork/src/ofxTCPServer.cpp")
list(APPEND OF_ADDON_OFXNETWORK_LINK "../openFrameworks/addons/ofxNetwork/src/ofxTCPManager.cpp")
list(APPEND OF_ADDON_OFXNETWORK_LINK "../openFrameworks/addons/ofxNetwork/src/ofxTCPClient.cpp")
list(APPEND OF_ADDON_OFXNETWORK_LINK "../openFrameworks/addons/ofxNetwork/src/ofxNetworkUtils.cpp")
add_library(OF_ADDON_OFXNETWORK ${OF_ADDON_OFXNETWORK_LINK})

#ofxOpenCv
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/video")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/video/legacy")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/video/detail")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/flann")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/core")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/core/parallel")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/core/parallel/backend")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/core/hal")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/core/cuda")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/core/cuda/detail")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/core/utils")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/core/opencl")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/core/opencl/runtime")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/core/opencl/runtime/autogenerated")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/core/detail")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/imgproc")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/imgproc/hal")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/imgproc/detail")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/objdetect")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/ml")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/dnn")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/dnn/utils")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/features2d")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/features2d/hal")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/photo")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/photo/legacy")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv4/opencv2/calib3d")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/video")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/video/legacy")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/video/detail")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/flann")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/core")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/core/parallel")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/core/parallel/backend")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/core/hal")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/core/cuda")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/core/cuda/detail")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/core/llapi")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/core/utils")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/core/opencl")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/core/opencl/runtime")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/core/opencl/runtime/autogenerated")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/core/detail")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/core/private")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/core/openvx")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/stitching")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/stitching/detail")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/imgproc")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/imgproc/hal")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/imgproc/detail")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/objdetect")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/gapi")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/gapi/oak")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/gapi/s11n")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/gapi/gpu")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/gapi/util")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/gapi/python")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/gapi/cpu")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/gapi/render")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/gapi/fluid")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/gapi/streaming")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/gapi/streaming/onevpl")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/gapi/streaming/gstreamer")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/gapi/infer")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/gapi/plaidml")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/gapi/own")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/gapi/ocl")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/ml")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/imgcodecs")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/imgcodecs/legacy")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/dnn")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/dnn/utils")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/videoio")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/videoio/legacy")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/videoio/doc")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/highgui")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/features2d")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/features2d/hal")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/ts")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/photo")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/photo/legacy")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/libs/opencv/include/opencv2/calib3d")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv/src")
list(APPEND OF_ADDON_OFXOPENCV_INCLUDE "../openFrameworks/addons/ofxOpenCv")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libopencv_photo.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libopencv_calib3d.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libquirc.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libopencv_features2d.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libopencv_dnn.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libopencv_core.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/liblibopenjp2.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libopencv_video.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libopencv_ml.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/liblibprotobuf.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libopencv_objdetect.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libzlib.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libopencv_flann.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libittnotify.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/libs/opencv/lib/osx/libopencv_imgproc.a")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/src/ofxCvColorImage.cpp")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/src/ofxCvShortImage.cpp")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/src/ofxCvContourFinder.cpp")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/src/ofxCvHaarFinder.cpp")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/src/ofxCvImage.cpp")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/src/ofxCvFloatImage.cpp")
list(APPEND OF_ADDON_OFXOPENCV_LINK "../openFrameworks/addons/ofxOpenCv/src/ofxCvGrayscaleImage.cpp")
add_library(OF_ADDON_OFXOPENCV ${OF_ADDON_OFXOPENCV_LINK})

#ofxVectorGraphics
list(APPEND OF_ADDON_OFXVECTORGRAPHICS_INCLUDE "../openFrameworks/addons/ofxVectorGraphics/libs")
list(APPEND OF_ADDON_OFXVECTORGRAPHICS_INCLUDE "../openFrameworks/addons/ofxVectorGraphics")
list(APPEND OF_ADDON_OFXVECTORGRAPHICS_INCLUDE "../openFrameworks/addons/ofxVectorGraphics/src")
list(APPEND OF_ADDON_OFXVECTORGRAPHICS_LINK "../openFrameworks/addons/ofxVectorGraphics/libs/CreEPS.cpp")
list(APPEND OF_ADDON_OFXVECTORGRAPHICS_LINK "../openFrameworks/addons/ofxVectorGraphics/src/ofxVectorGraphics.cpp")
add_library(OF_ADDON_OFXVECTORGRAPHICS ${OF_ADDON_OFXVECTORGRAPHICS_LINK})

#ofxXmlSettings
list(APPEND OF_ADDON_OFXXMLSETTINGS_INCLUDE "../openFrameworks/addons/ofxXmlSettings/libs")
list(APPEND OF_ADDON_OFXXMLSETTINGS_INCLUDE "../openFrameworks/addons/ofxXmlSettings")
list(APPEND OF_ADDON_OFXXMLSETTINGS_INCLUDE "../openFrameworks/addons/ofxXmlSettings/src")
list(APPEND OF_ADDON_OFXXMLSETTINGS_LINK "../openFrameworks/addons/ofxXmlSettings/libs/tinyxmlparser.cpp")
list(APPEND OF_ADDON_OFXXMLSETTINGS_LINK "../openFrameworks/addons/ofxXmlSettings/libs/tinyxmlerror.cpp")
list(APPEND OF_ADDON_OFXXMLSETTINGS_LINK "../openFrameworks/addons/ofxXmlSettings/libs/tinyxml.cpp")
list(APPEND OF_ADDON_OFXXMLSETTINGS_LINK "../openFrameworks/addons/ofxXmlSettings/src/ofxXmlSettings.cpp")
add_library(OF_ADDON_OFXXMLSETTINGS ${OF_ADDON_OFXXMLSETTINGS_LINK})

#ofxEmscripten
list(APPEND OF_ADDON_OFXEMSCRIPTEN_INCLUDE "../openFrameworks/addons/ofxEmscripten/libs/html5video/include")
list(APPEND OF_ADDON_OFXEMSCRIPTEN_INCLUDE "../openFrameworks/addons/ofxEmscripten/libs/html5video")
list(APPEND OF_ADDON_OFXEMSCRIPTEN_INCLUDE "../openFrameworks/addons/ofxEmscripten/libs")
list(APPEND OF_ADDON_OFXEMSCRIPTEN_INCLUDE "../openFrameworks/addons/ofxEmscripten/libs/html5audio/include")
list(APPEND OF_ADDON_OFXEMSCRIPTEN_INCLUDE "../openFrameworks/addons/ofxEmscripten/libs/html5audio")
list(APPEND OF_ADDON_OFXEMSCRIPTEN_INCLUDE "../openFrameworks/addons/ofxEmscripten/src")
list(APPEND OF_ADDON_OFXEMSCRIPTEN_INCLUDE "../openFrameworks/addons/ofxEmscripten")
list(APPEND OF_ADDON_OFXEMSCRIPTEN_LINK "../openFrameworks/addons/ofxEmscripten/src/ofxEmscriptenSoundStream.cpp")
list(APPEND OF_ADDON_OFXEMSCRIPTEN_LINK "../openFrameworks/addons/ofxEmscripten/src/ofxEmscriptenVideoPlayer.cpp")
list(APPEND OF_ADDON_OFXEMSCRIPTEN_LINK "../openFrameworks/addons/ofxEmscripten/src/ofxEmscriptenSoundPlayer.cpp")
list(APPEND OF_ADDON_OFXEMSCRIPTEN_LINK "../openFrameworks/addons/ofxEmscripten/src/ofxEmscriptenVideoGrabber.cpp")
list(APPEND OF_ADDON_OFXEMSCRIPTEN_LINK "../openFrameworks/addons/ofxEmscripten/src/ofxEmscriptenURLFileLoader.cpp")
list(APPEND OF_ADDON_OFXEMSCRIPTEN_LINK "../openFrameworks/addons/ofxEmscripten/src/ofxAppEmscriptenWindow.cpp")
add_library(OF_ADDON_OFXEMSCRIPTEN ${OF_ADDON_OFXEMSCRIPTEN_LINK})

#ofxAccelerometer
list(APPEND OF_ADDON_OFXACCELEROMETER_INCLUDE "../openFrameworks/addons/ofxAccelerometer/src")
list(APPEND OF_ADDON_OFXACCELEROMETER_INCLUDE "../openFrameworks/addons/ofxAccelerometer")
list(APPEND OF_ADDON_OFXACCELEROMETER_LINK "../openFrameworks/addons/ofxAccelerometer/src/ofxAccelerometer.cpp")
add_library(OF_ADDON_OFXACCELEROMETER ${OF_ADDON_OFXACCELEROMETER_LINK})

#ofxSvg
list(APPEND OF_ADDON_OFXSVG_INCLUDE "../openFrameworks/addons/ofxSvg/libs/libxml2/include/libxml")
list(APPEND OF_ADDON_OFXSVG_INCLUDE "../openFrameworks/addons/ofxSvg/libs/libxml2/include")
list(APPEND OF_ADDON_OFXSVG_INCLUDE "../openFrameworks/addons/ofxSvg/libs/libxml2")
list(APPEND OF_ADDON_OFXSVG_INCLUDE "../openFrameworks/addons/ofxSvg/libs/svgtiny/include")
list(APPEND OF_ADDON_OFXSVG_INCLUDE "../openFrameworks/addons/ofxSvg/libs/svgtiny")
list(APPEND OF_ADDON_OFXSVG_INCLUDE "../openFrameworks/addons/ofxSvg/libs")
list(APPEND OF_ADDON_OFXSVG_INCLUDE "../openFrameworks/addons/ofxSvg/src")
list(APPEND OF_ADDON_OFXSVG_INCLUDE "../openFrameworks/addons/ofxSvg")
list(APPEND OF_ADDON_OFXSVG_LINK "../openFrameworks/addons/ofxSvg/libs/libxml2/lib/osx/xml2.a")
list(APPEND OF_ADDON_OFXSVG_LINK "../openFrameworks/addons/ofxSvg/libs/svgtiny/lib/osx/svgtiny.a")
list(APPEND OF_ADDON_OFXSVG_LINK "../openFrameworks/addons/ofxSvg/src/ofxSvg.cpp")
add_library(OF_ADDON_OFXSVG ${OF_ADDON_OFXSVG_LINK})

#ofxOsc
list(APPEND OF_ADDON_OFXOSC_INCLUDE "../openFrameworks/addons/ofxOsc/libs/oscpack/src/osc")
list(APPEND OF_ADDON_OFXOSC_INCLUDE "../openFrameworks/addons/ofxOsc/libs/oscpack/src")
list(APPEND OF_ADDON_OFXOSC_INCLUDE "../openFrameworks/addons/ofxOsc/libs/oscpack")
list(APPEND OF_ADDON_OFXOSC_INCLUDE "../openFrameworks/addons/ofxOsc/libs/oscpack/src/ip")
list(APPEND OF_ADDON_OFXOSC_INCLUDE "../openFrameworks/addons/ofxOsc/src")
list(APPEND OF_ADDON_OFXOSC_INCLUDE "../openFrameworks/addons/ofxOsc")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/libs/oscpack/src/osc/OscOutboundPacketStream.cpp")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/libs/oscpack/src/osc/OscTypes.cpp")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/libs/oscpack/src/osc/OscReceivedElements.cpp")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/libs/oscpack/src/osc/OscPrintReceivedElements.cpp")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/libs/oscpack/src/ip/IpEndpointName.cpp")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/libs/oscpack/src/ip/posix/NetworkingUtils.cpp")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/libs/oscpack/src/ip/posix/UdpSocket.cpp")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/libs/oscpack/src/ip/win32/NetworkingUtils.cpp")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/libs/oscpack/src/ip/win32/UdpSocket.cpp")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/src/ofxOscParameterSync.cpp")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/src/ofxOscMessage.cpp")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/src/ofxOscBundle.cpp")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/src/ofxOscReceiver.cpp")
list(APPEND OF_ADDON_OFXOSC_LINK "../openFrameworks/addons/ofxOsc/src/ofxOscSender.cpp")
add_library(OF_ADDON_OFXOSC ${OF_ADDON_OFXOSC_LINK})

#ofxGPS
list(APPEND OF_ADDON_OFXGPS_INCLUDE "../openFrameworks/addons/ofxGPS/src/iOS")
list(APPEND OF_ADDON_OFXGPS_INCLUDE "../openFrameworks/addons/ofxGPS/src")
list(APPEND OF_ADDON_OFXGPS_INCLUDE "../openFrameworks/addons/ofxGPS")
list(APPEND OF_ADDON_OFXGPS_INCLUDE "../openFrameworks/addons/ofxGPS/src/common")
list(APPEND OF_ADDON_OFXGPS_LINK "../openFrameworks/addons/ofxGPS/src/Android/ofxGPSImplAndroid.cpp")
add_library(OF_ADDON_OFXGPS ${OF_ADDON_OFXGPS_LINK})

#ofxUnitTests
list(APPEND OF_ADDON_OFXUNITTESTS_INCLUDE "../openFrameworks/addons/ofxUnitTests/src")
list(APPEND OF_ADDON_OFXUNITTESTS_INCLUDE "../openFrameworks/addons/ofxUnitTests")

#ofxThreadedImageLoader
list(APPEND OF_ADDON_OFXTHREADEDIMAGELOADER_INCLUDE "../openFrameworks/addons/ofxThreadedImageLoader/src")
list(APPEND OF_ADDON_OFXTHREADEDIMAGELOADER_INCLUDE "../openFrameworks/addons/ofxThreadedImageLoader")
list(APPEND OF_ADDON_OFXTHREADEDIMAGELOADER_LINK "../openFrameworks/addons/ofxThreadedImageLoader/src/ofxThreadedImageLoader.cpp")
add_library(OF_ADDON_OFXTHREADEDIMAGELOADER ${OF_ADDON_OFXTHREADEDIMAGELOADER_LINK})

#ofxAndroid
list(APPEND OF_ADDON_OFXANDROID_INCLUDE "../openFrameworks/addons/ofxAndroid/src")
list(APPEND OF_ADDON_OFXANDROID_INCLUDE "../openFrameworks/addons/ofxAndroid")
list(APPEND OF_ADDON_OFXANDROID_LINK "../openFrameworks/addons/ofxAndroid/src/ofxAndroidSoundPlayer.cpp")
list(APPEND OF_ADDON_OFXANDROID_LINK "../openFrameworks/addons/ofxAndroid/src/ofxAndroidVideoGrabber.cpp")
list(APPEND OF_ADDON_OFXANDROID_LINK "../openFrameworks/addons/ofxAndroid/src/ofxAndroidUtils.cpp")
list(APPEND OF_ADDON_OFXANDROID_LINK "../openFrameworks/addons/ofxAndroid/src/ofAppAndroidWindow.cpp")
list(APPEND OF_ADDON_OFXANDROID_LINK "../openFrameworks/addons/ofxAndroid/src/ofxAndroidSoundStream.cpp")
list(APPEND OF_ADDON_OFXANDROID_LINK "../openFrameworks/addons/ofxAndroid/src/ofxAndroidAccelerometer.cpp")
list(APPEND OF_ADDON_OFXANDROID_LINK "../openFrameworks/addons/ofxAndroid/src/ofxAndroidVibrator.cpp")
list(APPEND OF_ADDON_OFXANDROID_LINK "../openFrameworks/addons/ofxAndroid/src/ofxAndroidLogChannel.cpp")
list(APPEND OF_ADDON_OFXANDROID_LINK "../openFrameworks/addons/ofxAndroid/src/ofxAndroidVideoPlayer.cpp")
add_library(OF_ADDON_OFXANDROID ${OF_ADDON_OFXANDROID_LINK})

#ofxAssimpModelLoader
list(APPEND OF_ADDON_OFXASSIMPMODELLOADER_INCLUDE "../openFrameworks/addons/ofxAssimpModelLoader/libs/assimp/include/assimp")
list(APPEND OF_ADDON_OFXASSIMPMODELLOADER_INCLUDE "../openFrameworks/addons/ofxAssimpModelLoader/libs/assimp/include")
list(APPEND OF_ADDON_OFXASSIMPMODELLOADER_INCLUDE "../openFrameworks/addons/ofxAssimpModelLoader/libs/assimp")
list(APPEND OF_ADDON_OFXASSIMPMODELLOADER_INCLUDE "../openFrameworks/addons/ofxAssimpModelLoader/libs/assimp/include/assimp/port/AndroidJNI")
list(APPEND OF_ADDON_OFXASSIMPMODELLOADER_INCLUDE "../openFrameworks/addons/ofxAssimpModelLoader/libs/assimp/include/assimp/port")
list(APPEND OF_ADDON_OFXASSIMPMODELLOADER_INCLUDE "../openFrameworks/addons/ofxAssimpModelLoader/libs/assimp/include/assimp/Compiler")
list(APPEND OF_ADDON_OFXASSIMPMODELLOADER_INCLUDE "../openFrameworks/addons/ofxAssimpModelLoader/src")
list(APPEND OF_ADDON_OFXASSIMPMODELLOADER_INCLUDE "../openFrameworks/addons/ofxAssimpModelLoader")
list(APPEND OF_ADDON_OFXASSIMPMODELLOADER_LINK "../openFrameworks/addons/ofxAssimpModelLoader/libs/assimp/lib/osx/assimp.a")
list(APPEND OF_ADDON_OFXASSIMPMODELLOADER_LINK "../openFrameworks/addons/ofxAssimpModelLoader/src/ofxAssimpMeshHelper.cpp")
list(APPEND OF_ADDON_OFXASSIMPMODELLOADER_LINK "../openFrameworks/addons/ofxAssimpModelLoader/src/ofxAssimpAnimation.cpp")
list(APPEND OF_ADDON_OFXASSIMPMODELLOADER_LINK "../openFrameworks/addons/ofxAssimpModelLoader/src/ofxAssimpTexture.cpp")
list(APPEND OF_ADDON_OFXASSIMPMODELLOADER_LINK "../openFrameworks/addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.cpp")
add_library(OF_ADDON_OFXASSIMPMODELLOADER ${OF_ADDON_OFXASSIMPMODELLOADER_LINK})

#ofxiOS
list(APPEND OF_ADDON_OFXIOS_INCLUDE "../openFrameworks/addons/ofxiOS/src")
list(APPEND OF_ADDON_OFXIOS_INCLUDE "../openFrameworks/addons/ofxiOS")
list(APPEND OF_ADDON_OFXIOS_INCLUDE "../openFrameworks/addons/ofxiOS/src/video")
list(APPEND OF_ADDON_OFXIOS_INCLUDE "../openFrameworks/addons/ofxiOS/src/core")
list(APPEND OF_ADDON_OFXIOS_INCLUDE "../openFrameworks/addons/ofxiOS/src/app")
list(APPEND OF_ADDON_OFXIOS_INCLUDE "../openFrameworks/addons/ofxiOS/src/utils")
list(APPEND OF_ADDON_OFXIOS_INCLUDE "../openFrameworks/addons/ofxiOS/src/tvOS")
list(APPEND OF_ADDON_OFXIOS_INCLUDE "../openFrameworks/addons/ofxiOS/src/gl")
list(APPEND OF_ADDON_OFXIOS_INCLUDE "../openFrameworks/addons/ofxiOS/src/events")
list(APPEND OF_ADDON_OFXIOS_INCLUDE "../openFrameworks/addons/ofxiOS/src/sound")
list(APPEND OF_ADDON_OFXIOS_LINK "../openFrameworks/addons/ofxiOS/src/sound/ofxOpenALSoundPlayer.cpp")
list(APPEND OF_ADDON_OFXIOS_LINK "../openFrameworks/addons/ofxiOS/src/sound/SoundEngine.cpp")
add_library(OF_ADDON_OFXIOS ${OF_ADDON_OFXIOS_LINK})
